"""Shared pipeline primitives for enrichment and intake workflows."""

from .http_client import CachedHttpClient, HttpResponse
from .bibtex_io import (
    BibWriteIntegrityError,
    WriteFailureArtifacts,
    entry_key,
    entry_type,
    get_entry_map,
    parse_bib_file,
    parse_bib_text,
    resolve_bib_paths,
    transactional_write_bib_file,
    write_bib_file,
)
from .bibmeta import (
    BibmetaDiagnostic,
    BibmetaManifest,
    BibmetaManifestError,
    ResolvedBibmeta,
    discover_repo_bib_files,
    load_manifest as load_bibmeta_manifest,
    resolve_bibmeta,
    validate_bib_file as validate_bibmeta_file,
    validate_repo_bibmeta,
)
from .normalization import (
    equivalent_text,
    is_prefix_equivalent,
    normalize_spaces,
    normalize_text,
    sanitize_bibtex_text,
    strip_latex,
    word_count,
)
from .bibkey import (
    author_signature,
    author_token,
    entry_signature,
    generate_bib_key,
    is_key_format_valid,
    key_expected_year,
    keyword_candidates,
    keyword_token,
    normalize_year,
    parse_key_parts,
    suggest_bib_keys,
    synthesize_bib_key,
    validate_bib_key,
)
from .time_utils import now_iso, text_sha256

__all__ = [
    "CachedHttpClient",
    "HttpResponse",
    "BibWriteIntegrityError",
    "WriteFailureArtifacts",
    "entry_key",
    "entry_type",
    "get_entry_map",
    "parse_bib_file",
    "parse_bib_text",
    "resolve_bib_paths",
    "transactional_write_bib_file",
    "write_bib_file",
    "BibmetaDiagnostic",
    "BibmetaManifest",
    "BibmetaManifestError",
    "ResolvedBibmeta",
    "discover_repo_bib_files",
    "load_bibmeta_manifest",
    "resolve_bibmeta",
    "validate_bibmeta_file",
    "validate_repo_bibmeta",
    "equivalent_text",
    "is_prefix_equivalent",
    "normalize_spaces",
    "normalize_text",
    "sanitize_bibtex_text",
    "strip_latex",
    "word_count",
    "author_signature",
    "author_token",
    "entry_signature",
    "generate_bib_key",
    "is_key_format_valid",
    "key_expected_year",
    "keyword_candidates",
    "keyword_token",
    "normalize_year",
    "parse_key_parts",
    "suggest_bib_keys",
    "synthesize_bib_key",
    "validate_bib_key",
    "now_iso",
    "text_sha256",
]
